name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ unpl=V2_ZzNtbUEAS0B3DRVdLElfAGIDE11KVUAUJw5BB3hLVVFiVBYJclRCFnQURlVnGlUUZwcZXUpcQRRFCEdkeB5fA2AFEFlBZxVLK14bADlNDEY1WnwHBAJfFXYPR1Z6EVgBVzMRXXJXQiV2DUBdexpcAGEzIlpyZ3MXdwFOXXgpXTVmM1AJHlNBHHINQBl4HFoMZwASWERnQiV2; __jdu=247812147; areaId=18; ipLoc-djd=18-1501-29451-0; pinId=UTHY7CZ5HBu1ffsfn98I-w; pin=jianlove; unick=nycjian; ceshi3.com=201; _tp=FDDUpP3KBR6U2aPQ0W1V3w%3D%3D; _pst=jianlove; __jdv=76161171|google-search|t_262767352_googlesearch|cpc|kwd-126030955_0_2f9d34b8fa2441019320c76b2c8e4f5e|1603869634998; shshshfpa=6430dd5d-26c1-ce34-a949-561dd78bb191-1603869654; shshshfpb=p8fRyroYvQRQF8snJGdpfVg%3D%3D; mba_muid=247812147; shshshfp=e6f736d8d887e3fd7296d7a375db198b; 3AB9D23F7A4B3C9B=3JUYXHXFWJ5U3QDSMBAB7EGFQQB5ACSMD7IZEPLV3AV423WTGVM2GNQ3SS2NZ5GYAASROSMMDAEFYXZ3SCD6RKP5AU; jcap_dvzw_fp=3a20d829ef4d7a12e1390065557c03a2$89134187754; __jdc=122270672; thor=759644EFC43AE01FF3FAAAF3774D7F9984E41C82446BE2A424D1935BC3AF460BDDBB0BBEFD9D20103162C5AD5006F9EFE305CD99E6D5FFAE97193C851229F9C0C9F12DDCF498867A10147F16B0DFE4003F52CF0FA97BE73A25596B6BEAE601CE83348CCE9D9AF9FBFE9023DE152B90271B24515210EA69928C2CE7202360A0D842A9C9873CE36ED0CC240FE94AC5240D; TrackerID=DOrZtjaRzBnjcEMQQlKsZkGP_D__DG0voaLjiLqPu-cETTwb_LsjfOQXKWQpjaUM7prQXdNePhtaEBn6aK1_-dBq20AdU8rgfncnwnUIQ4EEaCjcJ2ZUQqiu2zXqT3nM; pt_key=AAJfmR5kADAZGQ09qAKjrc4ESYptipZS-Jmqa87u8-4RoSew1gKJwFKVcObhWuu3zM-99NJrI_4; pt_pin=jianlove; pt_token=0c2d2ojn; pwdt_id=jianlove; sfstoken=tk01m00a41d8aa8sMiszUlRHYlhjclpTIMvVCuGseMno0uE7NqTqSsCfjvxOz1NMAwl6UkUFZAw7QFTh7Y7EuZI8nDrs; RT="z=1&dm=jd.com&si=nqkhq83hcmh&ss=kgt2wewf&sl=3&tt=0&obo=3&nu=d41d8cd98f00b204e9800998ecf8427e&cl=2td5&ld=2vf1&r=099562ffd526e655e2193f9c206b4f2d&ul=2vf4&hd=2vvw"; mobilev=html5; __jda=122270672.247812147.1603869583.1603869590.1603930397.2; __jdb=122270672.1.247812147|2.1603930397; mba_sid=16039303975915285600377017772.1; __jd_ref_cls=MJingDouHome_NewUserExpo;  }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ SCU3705T744f5bc48b3d28710fc66c27d211807458213f28c2879 }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


